version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .. 
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3001:3001"
      - "3002:3002"
      - "9229:9229" 
    volumes:
      - ..:/workspace:cached 
      - /workspace/node_modules  
    depends_on:
      - mongo
    networks:
      - db_network
    environment:
      NODE_ENV: development
    command: ["npx", "ts-node-dev", "--respawn", "--transpile-only", "--inspect=0.0.0.0:9229", "./src/index.ts"]

  mongo:
    container_name: mongo-container
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - db_network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoRoot
  

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoRoot
      ME_CONFIG_MONGODB_SERVER: mongo-container
    networks:
      - db_network
      # Password to log in admin:pass

networks:
  db_network:
    driver: bridge
volumes:
  mongo_data: